### ISSUE TITLE
HMS Core update ...

### ISSUE THREAD

**Issue by martrix78** [HMS-Core/hms-cordova-plugin#107]
**Description**
When I perform authorization, the HMS core update starts and ends with error 102
`this.HMSHealth.signIn([HuaweiHiHealth.HEALTHKIT_STEP_READ])`
request return errorCode: 8
**Expected behavior**
successful authorization

**Current behavior**
When I perform authorization, the HMS core update starts and ends with error 102
`this.HMSHealth.signIn([HuaweiHiHealth.HEALTHKIT_STEP_READ])`
request return errorCode: 8

**Logs**
https://pst.klgrth.io/paste/sy4ft

**Environment**
 - Platform: Ionic Framework  : @ionic/angular 5.6.5

 - Kit: Health
 - Kit Version: 5.0.5-302
 - OS Version: Android 10
 - Android Studio version: 2021.1.1. Patch 3 
 - Platform version Y5p
 - Node Version v12.22.12
 - Your Location/Region Russia

**Other**
HMS core v 6.7.0.301

**Comment by Xuejiao-Shi** [comment]
![image](https://user-images.githubusercontent.com/99166105/190939053-eb0a5a60-44eb-40ec-8232-db7bff5cd40c.png)
The log shows that the agconnect-services.json file is not configured. You can configure it based on [this docs](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrating-cordova-health-plugin-0000001074081527).
![image](https://user-images.githubusercontent.com/99166105/190939113-521b2846-15fd-497a-8bfd-8d2dad085dc8.png)

**Comment by martrix78** [comment]
on chtome console i got exeption errorCode: 6003

**Comment by xuxiapu** [comment]
@martrix78 Thank you for your feedback. From your feedback log, we found that the errorcode 6003 is the Incorrect signing certificate fingerprint. Please [refer to this link](https://developer.huawei.com/consumer/en/doc/development/hmscore-common-References/error-code-0000001050045846) for specific solutions.

**Comment by martrix78** [comment]
@Xuejiao-Shi the fingerprint in the console and the application is the same, but the documentation says:
`Open the APK file of an app, extract the META-INF directory from the file, obtain the CERT.RSA file in the directory, and run the keytool -printcert -file META-INF/CERT.RSA`
but this file is not in the directory META-INF
I sign the apk through android studio...

**Comment by xuxiapu** [comment]
If a signature file has been configured in your project, you can compile the project by clicking here
![image](https://user-images.githubusercontent.com/114389983/194686462-37081222-5e4c-40d0-ba78-d3847c0205cc.png)
. After compiling, open the compiled apk to check whether CERT exists RSA, or directly run the command "keytool - printcert - jarfile app. apk" to view the signature certificate information and check whether it is consistent with the signature configured on AppGallery Connect. If it is newly configured, the cache time may be about 10 minutes.

If there is no signature file configured in your project, please refer to the[ "Importing the Keystore File" guide](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/change-0000001050170085).

If you want to generate a new signature file, please check the [link](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/signing-fingerprint-0000001059050363).

If there is still a problem, please provide complete log information or your packaged apk.
