### ISSUE TITLE
ads-prime not support latest cordova

### ISSUE THREAD

**Issue by merbin2012** [HMS-Core/hms-cordova-plugin#112]
Currently latest cordova available (cordova-android 11), but if we are installing the **cordova plugin add @hmscore/cordova-plugin-hms-adsprime** plugin it show the following error "Cannot set properties of null (setting 'text')"

So I have downgraded the Cordova version to 10.1.1, and now it is working. Please update this plugin to work for Cordova-android 11 version

**Comment by xuxiapu** [comment]
Thanks for your feedback about the new release of cordova.

We have noticed the latest release of Cordova and will be adapted in future HMS versions. However, the version plan has not yet been confirmed. Please pay attention to the update information on the developer website.

**Comment by furkanaydgn** [comment]
Hello @merbin2012,

 **"Cannot set properties of null (setting 'text')"** error that you have encountered has been resolved with the latest update of **@hmscore/cordova-plugin-hms-adsprime**. 

You can use this [link ](https://www.npmjs.com/package/@hmscore/cordova-plugin-hms-adsprime) to download the latest  version of Huawei Cordova Ads-Prime.

For more information about Huawei Cordova Ads-Prime, you can access its official documentation via this [link](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050312764).
