### ISSUE TITLE
Plugin breaks reflection: java.lang.AssertionError: Built-in class kotlin.Any is not found

### ISSUE THREAD

**Issue by kristiyanP** [HMS-Core/hms-cordova-plugin#128]
**Description**
When I add the cordova push plugin on cordova 10&11 the plugin breaks reflection code.
Steps to reproduce:
Create class
```kotlin
class HelloPrinter() {

    companion object {
        fun test(){
            HelloPrinter::class.java.methods
                .filter { it.name =="helloWorld" }
                .mapNotNull { it.kotlinFunction }
                .forEach { it.call() }
        }
    }

    fun helloWorld() {
        Log.e("Hello", "world")
    }
}
```

Invoke test method in **MainActivity  extends CordovaActivity**
```java
 @Override
public void onCreate(Bundle savedInstanceState){
       // ....
      com.bandyer.cordovasampleapp.HelloPrinter.Companion.test();
}
```

**Expected behavior**
That everything works.

**Current behavior**
java.lang.AssertionError: Built-in class kotlin.Any is not found

**Environment**
 - Platform: Cordova
 - Kit: Push
 - Kit Version 6.7.0-300
 - OS Version 13
 - Android Studio version (if applicable) Flamingo 2022.2.1 Patch 1
 - Platform version (if applicable) MacOS - 13.0.1
 - Node Version (if applicable) node 14
 - Your Location/Region (if applicable)  Italy

**Other**
From my debug it looks like that applying the plugin with afterEvaluate breaks the kotlin reflection
https://github.com/HMS-Core/hms-cordova-plugin/blob/master/cordova-plugin-hms-push/src/android/build-extras.gradle#L41-L49
In fact if you modify it as the capacitor way it works.

**Comment by ozkulbeng** [comment]
Hi @kristiyanP 

Thank you for your contribution, it is highly appreciated. 🎉 
Due to our internal development and release flow & checks, we can't merge your PR directly. You can be sure that the fix will be released with our next major update.
