### ISSUE TITLE
event onRemoteMessageReceived not fire

### ISSUE THREAD

**Issue by VChuharev** [HMS-Core/hms-cordova-plugin#130]
the event in Remote Message Received is not triggered at any state of the application.

plugin version 6.9.0-300
platform android 11.0.0

there is an event in Logcat:
`javascript:hmsEventHandler('REMOTE_DATA_MESSAGE_RECEIVED', {"msg":{"collapseKey":"-1","data":"{'type':'intercom'}","dataOfMap":"{type=intercom}","messageId":"ABAAstMf5WR4QPhkeGgIAKY88UQ6eTcAAAA","originalUrgency":"1","urgency":"2","ttl":"10000","sentTime":"1685602552745","from":"99536292102848687","token":"IQAAAACy0x_lAADrYnZdzQRMjFn1DM_8hD4TcEqIsNgOiexmZRipoQER08RKZqhimHkYaYjPPJx1_vjhfqIhL4dOy83TLpqzVd1E1pnr_421WahJNg","receiptMode":"0","sendMode":"0","contents":"0","analyticInfo":"{\"biTag\":\"the_sample_bi_tag_for_receipt_service\"}","analyticInfoMap":"{biTag=the_sample_bi_tag_for_receipt_service}","titleLocalizationArgs":"[]","bodyLocalizationArgs":"[]","ImageUrl":"null","Link":"null","NotifyId":"0","When":"null","LightSettings":"[]","BadgeNumber":"null","Importance":"0","vibrateConfig":"[]","visibility":"null","isAutoCancel":"true","isLocalOnly":"true","isDefaultLight":"true","isDefaultSound":"true","isDefaultVibrate":"true"}})`

**Comment by ilsafarber** [comment]
Hi @VChuharev,

If an uplink message is successfully sent by your app to your app server and the server responds to the message, a receipt will be sent to your app through the **onRemoteMessageReceived()** listener.

Have you enabled uplink message receiving through HTTPS in AppGallery Connect?  [This document](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/sending-uplink-messages-0000001056558384) may help you.

**Comment by VChuharev** [comment]
> Hi @VChuharev,
> 
> If an uplink message is successfully sent by your app to your app server and the server responds to the message, a receipt will be sent to your app through the **onRemoteMessageReceived()** listener.
> 
> Have you enabled uplink message receiving through HTTPS in AppGallery Connect? [This document](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/sending-uplink-messages-0000001056558384) may help you.

Thk. But I need to get data in the application from a message sent from the server, and not vice versa.

**Comment by Cubaza** [comment]
Hi,
I have same issue. @VChuharev have You maybe solve it? I've got information about event in logcat but nothing happen in JS code.

**Comment by VChuharev** [comment]
> 
Init new function

    function hmsEventHandler(data, data2) {
      if(data2) {
        console.log(data2.msg;) 
      }
    }

when the date push arrives, the application generates a call to this function, then what needs to be done.

**Comment by Cubaza** [comment]
@VChuharev thank You very much. This was an issue and now everything is working fine. Thank You very much.

**Comment by iand2x2** [comment]
@Cubaza hi, may I know how did you fix it?

**Comment by Cubaza** [comment]
@iand2x2 I've created new global function with body posted by VChuharev in this message:
https://github.com/HMS-Core/hms-cordova-plugin/issues/130#issuecomment-1601307985
So in my code it looks like this:
`
window.hmsEventHandler = function(eventName, payload) {
            if(eventName === 'REMOTE_DATA_MESSAGE_RECEIVED' && payload && payload['msg']) {
                HmsLocalNotification.localNotification({
                    [HmsLocalNotification.Attr.title]: payload['msg'].title,
                    [HmsLocalNotification.Attr.message]: new HmsPush.CordovaRemoteMessage(
                        payload['msg'].text
                    ).getDataOfMap(),
                });
            }
        }
`
That code make that when DATA push notification will be passed to application it will fire event and show notification. I know that there are more events which this code could broke, but for my purpose (showing notification on application) it is working.

**Comment by expcapitaldev** [comment]
@ozkulbeng hi, can you pls describe your changes here: https://github.com/HMS-Core/hms-cordova-plugin/commit/cd174a8c5e2fe7dfdc6fc58147f6cceddfb5c733#diff-071540fd2096627b7119d04b04c24066fd2196aee261a0c2f34dbb9475e51bd4R50

`if (window.hmsEventHandlers.hasOwnProperty(eventName)) {` you changed to `if (Object.prototype.hasOwnProperty(eventName)) {`

what is mean here `Object.prototype.hasOwnProperty` ?
Looks like it is a critical bug and we can not receive any events because here we will have every time `false`.
```
// call
window.hmsEventHandler('NOTIFICATION_OPENED_EVENT', {});
//
// if (Object.prototype.hasOwnProperty(eventName)) {
//            window.hmsEventHandlers[eventName].forEach((handler) => {
//                handler(data);
//            });
 //       }

 // eventName -> NOTIFICATION_OPENED_EVENT
 // Object - ?
 // Object.prototype.hasOwnProperty(eventName) - false, 


```

**Comment by expcapitaldev** [comment]
fixed 2 days ago https://github.com/HMS-Core/hms-cordova-plugin/commit/758a6e7623753e87f6a2b13867fe4ce585baee82
