### ISSUE TITLE
Push. Cordova dependency

### ISSUE THREAD

**Issue by suyundukov** [HMS-Core/hms-cordova-plugin#135]
**Description**
In latest update (6.10), `cordova` has been added as a dependency, I was wondering if there is a need for it. In my project `cordova` adds 5k. lines to my `package-lock.json`. I just can't find if `cordova` is used somewhere in project.

**Environment**
 - Platform: Capacitor/Cordova
 - Kit: Push
 - Kit Version: 6.10.0-300

**Other**
Also `@types/cordova` was added in `dependencies`, but it already exists in `devDependencies`.

**Comment by ozkulbeng** [comment]
Hello @suyundukov 
A new version of the [Cordova Push](https://www.npmjs.com/package/@hmscore/cordova-plugin-hms-push) plugin has been released. Please update to the latest version to get rid of this problem.

**Comment by suyundukov** [comment]
Thank you!
