### ISSUE TITLE
hms-map crashes app at map initialization

### ISSUE THREAD

**Issue by msg10** [HMS-Core/hms-cordova-plugin#15]
The app crashes when calling _HMSMap_ method _getMap_. No error is thrown before app closes. Other basic _HMSMap_ methods as _hasPermission_ or _setApiKey_ work, therefore the plugin is installed correctly. 

The issue is reproducible in simple sample project (I can grant access on git upon request), below is info on said project and environment. 

Plugin list:
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-hms-map 5.0.3.302 "cordova-plugin-hms-map"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"

Ionic info:
Ionic:
   Ionic CLI                     : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.0
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 11.0.0
   @angular/cli                  : 11.0.2
   @ionic/angular-toolkit        : 3.0.0

Cordova:
   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

Utility:
   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 1.0.0

System:
   Android SDK Tools : 26.1.1 
   NodeJS            : v14.5.0 
   npm               : 6.14.5

**Comment by bilginyuksel** [comment]
Hello @msg10, 
please share the piece of code you used to create map or you can give access to me of the sample project you've mentioned.

**Comment by msg10** [comment]
Thank you, @bilginyuksel ,just sent you the invite, let me know if there are any issues

**Comment by bilginyuksel** [comment]
Hello @msg10 ,
I don't see any problems with your code. I think you didn't set agconnect properly. When I ran the sample project you have provided, it worked.. Please follow the installation guide from the plugin's README.
_You can follow __2.4.1 Ionic with Cordova Runtime__ from the link below_.
[Map readme](https://github.com/HMS-Core/hms-cordova-plugin/tree/master/cordova-plugin-hms-map)

**Comment by msg10** [comment]
@bilginyuksel thank you so much! Could you take a look at the agconnect-services.json file, does it appear to be missing any variables maybe that are needed for mapkit? 

```
{
	"client":{
		"appType":"1",
		"cp_id":"89037*******",
		"product_id":"9105******",
		"client_id":"26578*****",
		"client_secret":"F6BDF855****",
		"project_id":"9105385*****",
		"app_id":"10****",
		"api_key":"******",
		"package_name":"****"
	},
	"configuration_version":"1.0"
}
```

**Comment by bilginyuksel** [comment]
[Map Cordova Huawei DOCS](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrating-cordova-plugin-0000001050329230). 
You can find the detailed explanation via clicking the link above but I think you are missing step 2 which is;
> Update the widget id property which is specified in the config.xml file. It must be same as the client > package_name value of the agconnect-services.json file. To obtain the agconnect-services.json file:.

**Comment by msg10** [comment]
@bilginyuksel the docs don't contain a sample agconnect. Therefore I cannot confirm it is properly generated and asked you.

But yes, the id's matched, so that wasn't the issue.

**Comment by aktug** [comment]
Hello @msg10 you can follow these steps at https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/config-agc-0000001050202026

**Comment by msg10** [comment]
@aktug using one method makes the app crash with no error messages, I'd call that an open issue

**Comment by aktug** [comment]
@bilginyuksel has looked at your app and your issue is related with agconnect

Please follow the steps at official docs carefully :
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/preparing-dev-0000001050444423
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/config-agc-0000001050202026
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/integrating-cordova-plugin-0000001050329230

Also, you can follow steps **2.4.1 Ionic with Cordova Runtime** from the link below.
https://github.com/HMS-Core/hms-cordova-plugin/tree/master/cordova-plugin-hms-map

After that, if the issue continues, please share logcat output, there should be any error message in there

Thank you for your understanding

**Comment by bilginyuksel** [comment]
Hello @msg10 ,

It was really timetaken to explain these to you. But we are here to help. You should've follow the instructions step by step to achieve it. Now I will share the commands I have used to run your demo.
```bash
> git clone https://github.com/msg10/hms-map-sample.git
> cd hms-map-sample
> npm install
> ionic integrations enable cordova
// I changed the widget_id from io.ionic.starter to same app id that I have in agconnect.
> ionic cordova plugin add @hmscore/cordova-plugin-hms-map
> cp -r node_modules/@hmscore/cordova-plugin-hms-map/ionic/dist/hms-map node_modules/@ionic-native/
> ionic cordova platform add android
> cp ../agconnect_services.json platforms/android/app/  // I copied my agconnect to platforms/android/app
> ionic cordova run android
```

These are the commands I have used to run your sample project.
And the final result is like below.

![Screenshot_20201222_180709_com bilginyuksel demo](https://user-images.githubusercontent.com/42303821/102903068-e1d0eb00-4480-11eb-8758-9f83f668d707.jpg)

**Comment by bilginyuksel** [comment]
Hello @msg10 ,

You should've follow the instructions step by step to achieve it. Now I will share the commands I have used to run your demo.
```bash
> git clone https://github.com/msg10/hms-map-sample.git
> cd hms-map-sample
> npm install
> ionic integrations enable cordova
// I changed the widget_id from io.ionic.starter to same app id that I have in agconnect.
> ionic cordova plugin add @hmscore/cordova-plugin-hms-map
> cp -r node_modules/@hmscore/cordova-plugin-hms-map/ionic/dist/hms-map node_modules/@ionic-native/
> ionic cordova platform add android
> cp ../agconnect_services.json platforms/android/app/  // I copied my agconnect to platforms/android/app
> ionic cordova run android
```

These are the commands I have used to run your sample project.
And the final result is like below.

![map_issue_ss](https://user-images.githubusercontent.com/42303821/102904020-3032b980-4482-11eb-9480-62f89e6ac2e5.jpg)

**Comment by msg10** [comment]
Hey, @bilginyuksel  , thank you for responding, I apologise - I did not mean to insinuate you’re being deceiving in regards to the sample project working. Moreover, thank you for sharing your commands - now I can confirm with 100% certainly we’re running the app the same way.  

My point was that an error is unhandled and that is an open issue for whoever is responsible for the integrity of the plugin - moreover now I see there can be many reasons for this.

  Again, thank you for your help, I’ll leave my findings here in case they might help anyone in the future:
  
    I got to make my sample app work after I generated a completely new agconnect file (no clue what was wrong with the first one).
    
       Unfortunately, that did not help my main project. Turned out you can run an app that has onesignal plugin installed, but it will crash specifically when map from mapkit is initialised. No clue what other plugins are incompatible.

**Comment by hsyndeniz** [comment]
Hi @msg10 
Please make sure that the Map service is enabled in AppGallery Connect.
![Capture](https://user-images.githubusercontent.com/25802714/103215930-d28cea00-4925-11eb-823c-8d6a0cecb36f.PNG)

For details, please refer to [Enabling Services](https://developer.huawei.com/consumer/en/doc/distribution/app/agc-enable_service)

**Comment by msg10** [comment]
Thank you @hsyndeniz, yeah, the Map Kit was enabled when creating the first agconnect, but I did "turn it off and on again" before creating a new one, maybe that did the trick.
