### ISSUE TITLE
hms-map overlaying all app content, including ionic MenuController

### ISSUE THREAD

**Issue by msg10** [HMS-Core/hms-cordova-plugin#16]
With google maps plugin, it was possible to have overlay elements (such as custom buttons) be placed on top of a map by setting "position: absolute" for the custom element. Unfortunately, I can't find a way to place custom buttons on top of hms-map.

Moreover, it appears hms-map overlays all and any elements, including Ionic's built in MenuController (pictured below).

Issues are reproducible in sample project, I can give you access to it on git upon request.

![Sc](https://user-images.githubusercontent.com/42645830/103270457-a07c9600-49c0-11eb-9e94-b2c61b5a1d6c.jpg)

![S](https://user-images.githubusercontent.com/42645830/103270453-9d81a580-49c0-11eb-83c9-907e46ec7621.jpg)

**Comment by bilginyuksel** [comment]
Hello @msg10,
Yes we aware of this. We have fixed it but unfortunately we are waiting for the next release.

**Comment by msg10** [comment]
@bilginyuksel thank you for quick response - is there an approximate date for the release known?

**Comment by aktug** [comment]
new version will be released end of January 2021 👍 thanks for your interest
