### ISSUE TITLE
Plugin do not have onRequestPermissionResult. Cause plugin do not return when call requestPermissionsScan()

### ISSUE THREAD

**Issue by cempay** [HMS-Core/hms-cordova-plugin#17]
**Description**
Plugin do not have onRequestPermissionResult. Cause plugin do not return when call requestPermissionsScan()

**Environment**
 - Platform: Cordova

**Code fixed:**
//PermissionUtils.java:
public static final int CAMERA_PERMISSION_CODE = 100;

//HMSScan.java:
@Override
    public void onRequestPermissionResult(int requestCode, String[] permissions,
                                          int[] grantResults) throws JSONException {
        super.onRequestPermissionResult(requestCode, permissions, grantResults);
        for (int r : grantResults) {
            if (r == PackageManager.PERMISSION_DENIED) {
                Log.d(TAG, "Permission Denied!");
                callbackContext.error(scanError.toJSON());
                return;
            }
        }
        switch (requestCode) {
            case PermissionUtils.CAMERA_PERMISSION_CODE:
                callbackContext.success();
                break;
        }
    }

**Comment by fuatbakkal** [comment]
Hello @cempay

**Comment by fuatbakkal** [comment]
Hello @cempay 

Since you already fixed the issue and sent PR, I am closing this issue. I have explained the situation in #18 why PR cannot be merged because of the Huawei regulations.

Thanks for your contribution.
