### ISSUE TITLE
onNotificationOpenedApp not triggering

### ISSUE THREAD

**Issue by chehsing** [HMS-Core/hms-cordova-plugin#21]
**Description**
I trying to implement a navigation function by tapping notification but the onNotificationOpenedApp is not triggering when i try to tap on it. I double checked i implemented the plugins correctly. 

**Expected behavior**
onNotificationOpenedApp gets trigger with result.

**Current behavior**
onNotificationOpenedApp not getting trigger

**Other**
```
export class HMSPushUtils {
  constructor(
    private hmsPush: HmsPush,
    private hmsPushEvent: HmsPushEvent,
    private authService: AuthService,
    private storage: StorageUtils,
  ) {
    this.hmsPush.init();
    this.initiateListener();
  }

  initialize() {
    this.hmsPush.getToken().then((hmsToken) => {
      console.log("hmsToken", hmsToken);

      this.storage
        .getStorage(STORAGE_KEY.FCM)
        .then((token) => {
          if (token == null) {
            // Send hms token to backend to be stored
            this.authService.registerFcm(hmsToken).then((result) => {
              this.checkNotificationAllowed();
            });
          } else {
            this.checkNotificationAllowed();
          }
        })
        .catch((error) => console.log("getToken", error));
    });
  }

  private initiateListener() {
    this.hmsPushEvent.onTokenReceived((result) => {
      console.log("TOKEN_RECEIVED_EVENT", result.token);
    });

    this.hmsPushEvent.onTokenError((result) => {
      console.log("ON_TOKEN_ERROR_EVENT", result.exception);
    });

    this.hmsPushEvent.onNotificationOpenedApp((result) => {
      console.log("get");
      console.log("NOTIFICATION_OPENED_EVENT", result);
      // Show logic here
    });

    this.hmsPush
      .getInitialNotification()
      .then((result: any) => {
        console.log("getInitialNotification", result);
      })
      .catch((result: any) => {
        console.log("getInitialNotification", result);
      });
  }
```

**Environment**
 - Platform: Ionic
 - Kit: Push
 - Kit Version 5.0.2-301
 - OS Version Android 7
 - Platform version 4.11.10
 - Node Version 10.17

**Comment by chehsing** [comment]
I tried running my application on Android 10, it seems to be working fine. Is this function only working on Android 10 and above?

**Comment by mesutgedik** [comment]
Hi chehsing, First of all, I need some information to solve your issue. 

- Which one do you use Ionic Cordova or Ionic Capacitor ? 
- If you are using cordova runtime, what is the cordova cli version and cordova-android version ? 
- İf you are using capacitor runtime, what is the version of capacitor/core and capacitor/android ?  
- What is the angular/core version and Ionic/angular version ? 

If you give me these informations maybe I can help more.

For your second question's answer is onNotificationOpenedApp listener works Android 5.0 and above.

**Comment by chehsing** [comment]
hi mesutgedi, here's the information you requested:
- Ionic Cordova
- Cordova cli - 10.0.0
- Cordova Android - 9.0.0
- angular/core - 8.1.2
- ionic/angular - 4.11.10

I tried a few cases on the listener, so far this is what i got on my end.

**Physical device (with HMS Core)**
- Huawei P9 (Android 7) => not triggering
- Samsung Galaxy Note 10 (Android 11) => not triggering
- Honor View 20 (Android 10) => working
- Huawei P30 (Android 10) => working

**Huawei cloud debugging**
- Huawei P40 (Android 10) => working
- Huawei P30 Lite (Android 9) => not triggering

**Comment by mesutgedik** [comment]
Hello again chehsing , we are investigating the error you encountered, we will return as soon as possible.

**Comment by chehsing** [comment]
Hey, i'm able to narrowed it down. This issue seems to be happening when I sent it with notification message. Changing it to data message seems to resolved the issue.

![Screen Shot 2021-03-08 at 9 29 40 AM](https://user-images.githubusercontent.com/49464310/110263650-46b4cf80-7ff2-11eb-991d-1ad6776df9cb.png)
