### ISSUE TITLE
Version for Ionic v3

### ISSUE THREAD

**Issue by jenriquelopez** [HMS-Core/hms-cordova-plugin#31]
**Description**
I currently have my application built on Ionic V3. I need to integrate Huawei IAP into my application but I can't find a compatible version for Ionic V3. Is there any?

**Expected behavior**

**Current behavior**

**Screenshots**

**Logs**

**Environment**
 - Platform: Cordova
 - Kit: IAP
 - Kit Version: 5.0.4
 - OS Version  Android 10

**Other**

**Comment by hsyndeniz** [comment]
Hello @jenriquelopez ,
I created an application with Ionic v3 and tried with Cordova HMS IAP Plugin.
It works but if you still get the error, you can try importing the library in a different way.

Try to declare a variable instead of importing the library.
`declare var HMSInAppPurchases;
`
