### ISSUE TITLE
PendingIntent security vulnerability on Google Play Store Android App

### ISSUE THREAD

**Issue by casper5822** [HMS-Core/hms-cordova-plugin#46]
**Description**
Description of what the issue is about
We use hms-cordova-plugin in our ionic 5 app and we have this up on Google Play Store too.
Google send us a message with a vulnerability problem with PendingIntent that it is used only in this class:

**HmsLocalNotificationController**

And this is  the Google alert message:

We reviewed your app, with package name xx.xxx.xxx, and found that your app uses software that contains security vulnerabilities for users. Apps with these vulnerabilities can expose user information or damage a user’s device, and may be considered to be in violation of our Malicious Behavior policy.

Below is the list of issues and the corresponding APK versions that were detected in your recent submission. Please migrate your apps to use the updated software as soon as possible and increment the version number of the upgraded APK

how to fix this problem is here:

https://support.google.com/faqs/answer/10437428

Google Deadline to fix this bug: 14 September 2021.

**Expected behavior**
What you expected to happen？
how to fix this problem is here:

https://support.google.com/faqs/answer/10437428

**Current behavior**
What actually happened？
Our app doesn't pass the google play console security checks. 

**Environment**
 - Platform: Ionic 5 with capacitor
 - Kit:
    "@hmscore/cordova-plugin-hms-push": "^5.1.1-301",
    "@hmscore/ionic-native-hms-push": "^5.1.1-301",
 - Kit Version [e.g. 5.0.3]
 - OS Version [e.g. Android 11]
 - Android Studio version 4.2.1
 - Platform version (if applicable)
 - Node Version v14.17.1
 - Your Location/Region: Europe

**Comment by casper5822** [comment]
Hello, is there any update on this problem?

**Comment by casper5822** [comment]
@aktug I talked to Huawei official support and they said that this bug has been fixed in the new hmscore version 5.3.0.304. So I kindly ask for the plugin update to the new core version.

**Comment by aktug** [comment]
https://www.npmjs.com/package/@hmscore/cordova-plugin-hms-push/v/5.3.0-304 released @casper5822
