### ISSUE TITLE
(documentation) describe push API Methods

### ISSUE THREAD

**Issue by expcapitaldev** [HMS-Core/hms-cordova-plugin#7]
Good day.
Could you describe API methods https://github.com/HMS-Core/hms-cordova-plugin/tree/master/cordova-plugin-hms-push#3-cordova-sdk-api-methods--constant-definitions ?

**Comment by aktug** [comment]
Hello @expcapitaldev ;
You can find the API Reference from https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References/functions-0000001050135733

**Comment by expcapitaldev** [comment]
thank you @aktug
