### ISSUE TITLE
when drag the map show grid

### ISSUE THREAD

**Issue by alextapia007** [HMS-Core/hms-cordova-plugin#71]
**Description**
when drag the map show grid
And if the div is inside other div. it cant drag.

**Expected behavior**
load the map

**Current behavior**
dont load the map

**Screenshots**
![Screenshot_20211013_140716_com lifeclub connect](https://user-images.githubusercontent.com/15269078/137198040-b60b8ee1-bf0d-439f-ab09-4acbf5c126e5.jpg)

**Environment**
 - Platform: cordova
 - Kit: map
 - Kit Version 5.2.300
 - OS Version android 10

**Comment by tolunaykatirci** [comment]
Hello @alextapia007,

Can you please make sure your App is successfully configured and you have internet connection?

To configure the App information in AppGallery Connect, you can follow the document below:
https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/config-agc-0000001050202026

If your problem continues, can you share logs so we can examine the problem in detail?
