### ISSUE TITLE
scan插件在扫码界面的标题怎么设置

### ISSUE THREAD

**Issue by 361877802** [HMS-Core/hms-cordova-plugin#72]
scan插件在扫码界面的标题怎么设置，默认是Scan,好像调用的时候没有这方面的设置参数

环境
平台：cordova
套件：scan
套件版本 1.3.1-302
操作系统版本 android 11

**Comment by bagcimukremin** [comment]
Hello @361877802,

This Cordova plugin is a wrapper arround Native SDK and and native Huawei Scan Kit does not support changing default scan view title.
For question related to Native SDKs please [submit a ticket online](https://developer.huawei.com/consumer/en/support/feedback/).
