### ISSUE TITLE
Banner ads overlapping the page

### ISSUE THREAD

**Issue by merbin2012** [HMS-Core/hms-cordova-plugin#74]
The banner ads are displayed over the app content.
![1642656960920](https://user-images.githubusercontent.com/3687184/150279856-87f415a3-84b3-4346-af6e-8230172544ac.JPEG)

**Comment by sinemsevilmis** [comment]
Hi @merbin2012,

Could you please explain your problem in more detail and share a sample code to reproduce your error?

Thank you for your interest.

**Comment by merbin2012** [comment]
I didn't not expected huwai provide this much worst experience, see the date of issue opened, and your reply. Any more I'll remove all app from huwai store and leave huwai ads. 🤮

**Comment by SerdarCanDev** [comment]
Hi @merbin2012 , as @sinemsevilmis  said we couldn't reproduce your issue, we can only help you if you provide a detailed explanation of your problem and a minimum reproducible project or sample code if possible. Since we didn't get any response from you over the past month we have closed the ticket yet if your problem still exist you can always re-open the issue.

**Comment by merbin2012** [comment]
So is it good after 3months reply. Solving issues are second, first you have to give proper response soon as possible.

**Comment by SerdarCanDev** [comment]
Huawei's official HMS Cordova plugins are wrappers of native HMS kits, thus when we encounter an issue on one of our kits we first try our native demo applications, Cordova demo application and other platform kits such as Flutter or React Native. The problem solving process of bugs may take some time regarding the provided very limited information from your side and the running process of updates and other plugin maintenances, sorry for the inconvenience. 

I'm re-opening the issue, for further investigation please provide a detailed explanation of your problem and a minimal reproducible sample code or project if possible.

**Comment by merbin2012** [comment]
Ok
