### ISSUE TITLE
"Your app is not compliant with Google Play Policies"

### ISSUE THREAD

**Issue by nunoarruda** [HMS-Core/hms-cordova-plugin#81]
Hello HMS team,

I have a [Capacitor](https://capacitorjs.com/)-based Android app that is deployed to both Google Play and AppGallery. I am using `@hmscore/cordova-plugin-hms-push` v6.1.0-300 to enable push notifications for Huawei users.

Today I received this email:

![google-play-huawei-email](https://user-images.githubusercontent.com/1189149/158840677-cdf900a5-5653-4718-b53e-c3a42dc02e8d.png)

I guess the more important part is this:

```
Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Huawei Mobile Services SDK which contains code to download or install applications from unknown sources outside of Google Play.

After 120 days, new app releases containing this non-compliant version of this SDK will be rejected. This SDK version violates Device & Network Abuse policy.

Given the nature of the SDK, we request that you remove it from the version of your app submitted to the Play Store.
```

It looks like other apps are having the same problem:
👉 [Huawei Mobile Services SDK violation Device and Network Abuse policy](https://stackoverflow.com/questions/71508566/huawei-mobile-services-sdk-violation-device-and-network-abuse-policy)
👉 [Google Play ataca a los desarrolladores que usan los servicios de Huawei: 120 días para rectificar](https://androidtr.es/2022/03/17/google-play-ataca-a-los-desarrolladores-que-usan-los-servicios-de-huawei-120-dias-para-rectificar/)
👉 [关于谷歌商店（Google Play Store）应用因 不合规版本的华为移动服务 SDK 下架](https://ask.dcloud.net.cn/question/141433)
👉 [non-compliant version of HMS SDK](https://forums.developer.huawei.com/forumPortal/en/topic/0201828851586060012)

Have you identified the issue? Is there a fix?

Thanks in advance.

**Comment by Xuejiao-Shi** [comment]
Thank you for providing the information regarding this issue. We are very sorry that it brings you inconvinience and are now investigating the root cause of it.
Could you kindly help us with some information to locate this issue?
1. pls leave your APPID, app name and package name.

2. whether configured the following metadata in your app？

```
<meta-data 
android:name="com.huawei.hms.client.channel.androidMarket" 
android:value="false" />
```

**Comment by nunoarruda** [comment]
@Xuejiao-Shi 

1. My app ID is `105279813`, app name is `Pulse Grow`, and package name is `com.pulsegrow`

2. I don't have that metadata in my app

**Comment by Xuejiao-Shi** [comment]
@nunoarruda Your request has been received. We are aware of this issue and are currently investigating. Your application experience won't be affected at this time and we will continue to update you on solutions. Thanks for your understanding and support.

**Comment by vjfuenzalida** [comment]
Is this solved?
It happened to me using v5.3.0-305

**Comment by nunoarruda** [comment]
I've upgraded `@hmscore/cordova-plugin-hms-push` from v6.1.0-300 to v6.3.0-302, replaced `com.huawei.hms:push:6.1.0.300` with `com.huawei.hms:push:6.3.0.302`, and deployed a new version of my Android app to Google Play. So far so good, Google hasn't complained yet but I'm not 100% sure if this issue is fixed. @Xuejiao-Shi can you confirm?

**Comment by Xuejiao-Shi** [comment]
@nunoarruda The latest version of the cordova plugin has not been released yet. We will modify it as soon as possible. Please wait for the update.

**Comment by furkanaydgn** [comment]
The new version of  [@hmscore/cordova-plugin-hms-push](https://www.npmjs.com/package/@hmscore/cordova-plugin-hms-push) 6.3.0.304 has been released. The plugin is officially bumped to 6.3.0.304 sdk version.

**Comment by Xuejiao-Shi** [comment]
hi @nunoarruda @vjfuenzalida , so far we have provided analytics, location, nearby, account, push, site, iap, hms-availability, ads, map, ml Cordova plugins new version for this issue. You could obtain the latest plugin from the official website: https://www.npmjs.com/~hmscore

**Comment by nunoarruda** [comment]
Yeah, I've been using `@hmscore/cordova-plugin-hms-push` v6.3.0-304 for a while now. No Google Play issues so far. Closing this issue.

**Comment by nunoarruda** [comment]
@Xuejiao-Shi  Ignore my previous comment. Yesterday (14 July 2022) I received another email from Google Play saying my app is not compliant again:

![non-compliant-again](https://user-images.githubusercontent.com/1189149/179222894-9f2e33fa-45c0-4cce-92e0-c4e34f8dd34e.png)

I'm using [@hmscore/cordova-plugin-hms-push](https://www.npmjs.com/package/@hmscore/cordova-plugin-hms-push) v6.3.0-304.

Please take action.

**Comment by Xuejiao-Shi** [comment]
@nunoarruda pls check whether an old APK version is not updated in Testing Track on Google Play Console.

**Comment by Xuejiao-Shi** [comment]
@nunoarruda Please check the apk in Testing Track on Google Play Console. Ensure that the APK on all channels are using of the latest HMS Core SDK version.

**Comment by nunoarruda** [comment]
@Xuejiao-Shi thanks for the information. I indeed have an older version of my app in "Closed testing". I will try to replace it and see how it goes...
<img width="1107" alt="Screenshot 2022-07-18 at 10 15 14" src="https://user-images.githubusercontent.com/1189149/179481231-a9c7cf82-a95c-40fb-937c-eb2d2bbdc084.png">

**Comment by IberiaDroid** [comment]
I am having the same issue with the Internal Test version I uploaded yesterday. That Google Play message specifies that last release version of my app. 
I am using these libraries:

implementation 'com.huawei.hms:iap:6.4.0.301' 
implementation 'com.huawei.agconnect:agconnect-core:1.7.0.300' 
implementation 'com.huawei.hms:maps:6.5.1.300' 
implementation 'com.huawei.hms:location:4.0.4.300'
implementation 'com.huawei.hms:game:6.6.0.301' 

classpath 'com.huawei.agconnect:agcp:1.6.0.300'

Thanks a lot for your help

**Comment by coolleizhu** [comment]
@IberiaDroid The location kit in your project is not updated, you should use 
com.huawei.hms:location:6.4.0.300

Another thing, do you need to use game service in google play package? If not, it is suggested to remove this service from Google Play package.

After upgrade package, can you tell me the release result? Passed or failed again.

Thank you.

**Comment by IberiaDroid** [comment]
Thanks. I have upgraded the Location Kit and removed the Game kit. I used the Game kit to check if there are an update for my app in the Huawei Gallery. Right now my app will not have the option to check itself for updates in Huawei Gallery, but I do not mind, because my main goal is to have it ready in Google Play and I don't want trouble with them.
I do not know so far if my new release has passed, I assume I will have to wait a few hours or days to be reviewed. I will post here if the release has failed.
Thanks a lot for your help.

**Comment by earfire33** [comment]
Hello,

I have the same issue. I'm using the bluesource choicesdk. 
In my build.gradle file, I have :
 implementation 'at.bluesource.choicesdk:choicesdk-location:0.3.0'

and dependencies : 
classpath 'com.huawei.agconnect:agcp:1.4.2.300'

Could you help me please

Thanks in advance

**Comment by Xuejiao-Shi** [comment]
@nunoarruda Can you provide the download link of your app in Google Play for us to check?

**Comment by earfire33** [comment]
Hello, @nunoarruda , Below is th elink to my app in Google Play : 
https://play.google.com/store/apps/details?id=com.chacon.dioone

**Comment by Xuejiao-Shi** [comment]
@earfire33 Thank you for your feedback, it seems like you have integrated Push and location SDK in your project, please upgrade them to the latest version:[cordova-plugin-hms-push 6.3.0-304](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050135703).   [cordova-plugin-hms-location 6.4.0-300](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/version-change-history-0000001050142197)

 See more info on [HMS Core SDK Version Updates](https://stackoverflow.com/a/72474416/13329100).

**Note**: Before submitting a release to Google, also need to check the apk in Testing Track on Google Play Console. Ensure that the APK on all channels are using of the latest HMS Core SDK version.

**Comment by earfire33** [comment]
Hello again  @nunoarruda , 
the problem is in my app I don't use any reference directly to cordova stuff . I use  bluesource choicesdk.  

https://github.com/bluesource/ChoiceSDK

In my build.gradle file, I have :
implementation 'at.bluesource.choicesdk:choicesdk-location:0.3.0'

So, I think this Choice SDK should be modified

Thanks for your reply

**Comment by earfire33** [comment]
Hello @Xuejiao-Shi,  do you have any suggestions for my case ? 
Thanks again for your reply

**Comment by Xuejiao-Shi** [comment]
@earfire33 You are integrated through a third-party dependency. Before the new version of those plug-in released, You are advised to modify the dependency locally. The method Manually modifying the dependency kindly check [this link](https://stackoverflow.com/a/69159591/13329100).

**Comment by IberiaDroid** [comment]
@coolleizhu [coolleizhu](https://github.com/coolleizhu)
Sorry, the app has been rejected again with the same issue. I guess I would have to manually remove all the libraries from HMS. Of course I am not going to have two different codes to maintain. To be honest I don't have many users in Huawei, but I have a million downloads in Google Play. I am afraid I will have to give it up with HMS.

**Comment by coolleizhu** [comment]
@IberiaDroid 
Sorry to hear that. 
Can you share us how google reject the package update? Do they leave any message to you? 
You can send the information to hmscore@huawei.com.

I got some information that Google Play request developer to update the packages in all the track(including test track):

https://support.google.com/googleplay/android-developer/answer/2477981#warnings&zippy=%2Cwarnings%2C%E8%AD%A6%E5%91%8A

Hope it can help you.

BTW, I think you still can keep your package in AppGallery.

**Comment by IberiaDroid** [comment]
@coolleizhu 
My last several updates were rejected. I even appealed Google Play and I got this answer:
```
This is the message I got from Google
During review, we found that your app is not compliant with the Device and Network Abuse policy. 

Apps that cause users to download or install applications from unknown sources outside of Google Play are prohibited. Please note that you are responsible for all aspects of your app; by using an SDK in your app, you are responsible for how that SDK behaves within your app.
Apps and app listings on Google Play must not provide any means to activate or access functionality that violate these terms, such as linking to a non-compliant APK hosted outside Google Play.
You can read through the [Device and Network Abuse](https://support.google.com/googleplay/android-developer/answer/9888379) policy page for more details.

For example, your app is using a non-compliant version of Huawei Mobile Services SDK which contains code to download or install applications from unknown sources outside of Google Play. 

Given the nature of the SDK, we request that you remove it from the version of your app submitted to the Play Store.

Please resolve this issue within 30 days of the initial issuance of the warning or your app will be removed from Google Play.
```

Thanks

**Comment by Xuejiao-Shi** [comment]
hi @IberiaDroid  Could you mind to send us your the rejected package? We can help to review if any HMS Core SDK is not updated. If it is OK, You can send it to hmscore@huawei.com.

**Comment by Zee604** [comment]
Hi @Xuejiao-Shi 
I have the same issue. I have recieved the email from google play that your app has been rejected and it violating the terms and policies. They mentioned your app is using the HMS sdk version that is not compilaint with google play policies.
I'm using these following dependencies fore image background removing:

  // Import the base SDK for image segmentation.
    implementation 'com.huawei.hms:ml-computer-vision-segmentation:3.5.0.303'
    // Import the multiclass segmentation model package.
    implementation 'com.huawei.hms:ml-computer-vision-image-segmentation-multiclass-model:3.5.0.303'
    // Import the portrait segmentation model package.
    implementation 'com.huawei.hms:ml-computer-vision-image-segmentation-body-model:3.5.0.303'
    // Import the base SDK for gesture detection.
    implementation 'com.huawei.hms:ml-computer-vision-handkeypoint:3.5.0.301'
    // Import the hand keypoint detection model package.
    implementation 'com.huawei.hms:ml-computer-vision-handkeypoint-model:3.5.0.303'
    
    
    Could you please help me for this issue.
    Thanks

**Comment by neobie** [comment]
implementation 'com.huawei.hms:push:6.7.0.300'
    implementation "com.huawei.agconnect:agconnect-remoteconfig:1.7.3.300"
    implementation 'com.huawei.hms:hwid:6.9.0.300'
    implementation 'com.huawei.hms:ads-prime:3.4.60.301'

With all the latest SDK, still rejected by Google with the same message.
