### ISSUE TITLE
cordova-hms-scan-plugin

### ISSUE THREAD

**Issue by fabianpie** [HMS-Core/hms-cordova-plugin#91]
The hms scan plugin never fires the scan result when using custom view. It happens just using the example

 - Platform: Cordova
 - Kit: Scan
 - Kit Version 1.3.1.302
 - OS Version EMUI 10.0.1

**Comment by furkanaydgn** [comment]
Hello @fabianpie 

We tried to reproduce your issue and ran our Scan kit demo, we have successfully got the result as shown below. I suggest you to try our demo app and if the error still persists, to explore the issue in detail, please share a sample code block of your project for us to reproduce your issue?

![image](https://user-images.githubusercontent.com/28219369/175310008-e19d41a8-8014-42d8-8936-36496625c79d.png)
